# rtsp-server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtsp-server
  labels:
    app: rtsp
    {{- include "MSM-RTSP.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: rtsp
  template:
    metadata:
      labels:
        app: rtsp
        sidecar.mediastreamingmesh.io/inject: "true"
    spec:
      containers:
        - name: rtsp-server
          image: "{{ .Values.serverImage.name }}:{{ .Values.serverImage.tag }}"
          imagePullPolicy: IfNotPresent
        - name: rtsp-client
          image: "{{ .Values.clientImage.name }}:{{ .Values.clientImage.tag }}"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /tmp
              name: movies
      volumes:
        - name: movies
          hostPath:
            path: /tmp
