apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    {{- include "MSM-RTSP.labels" . | nindent 4 }}
  name: mystream
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - backend:
          service:
            name: mystream-hls
            port:
              number: 8888
        path: /mystream
        pathType: Prefix
