# rtsp-svc
apiVersion: v1
kind: Service
metadata:
  name: mystream
  labels:
    app: rtsp
    {{- include "MSM-RTSP.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: rtsp
      port: 554
      targetPort: 554
      protocol: TCP
  selector:
    app: rtsp
