kubernetesDistro: "K3S" #change this to desired Kubernetes Distribution e.g. "K8S" or "K3S"

controlPlaneIP: "{{ if eq .Values.kubernetesDistro \"K8S\" }}10.96.3.1{{ else if eq .Values.kubernetesDistro \"K3S\" }}10.43.3.1{{ end }}"

webhookClusterIP: "{{ if eq .Values.kubernetesDistro \"K8S\" }}10.96.4.1{{ else if eq .Values.kubernetesDistro \"K3S\" }}10.43.4.1{{ end }}"

nodeSelector: "{{ if eq .Values.kubernetesDistro \"K8S\" }}{{ else if eq .Values.kubernetesDistro \"K3S\" }}true{{ end }}"

namespace: "{{ if eq .Values.kubernetesDistro \"K8S\" }}default{{ else if eq .Values.kubernetesDistro \"K3S\" }}gbear{{ end }}"  #change the gbear to desired namespace for K3S.

cniClusterRole: msm-cni

cniConfigMap: msm-cni-config

webhookClusterRole: msm-admission-webhook-role

webhookClusterRoleBinding: msm-admission-webhook-binding

webhookServiceAccount: msm-admission-webhook-sa

gatewayDaemonSet: msm-gateway

gatewayName: gateway

webhookDeployment: msm-admission-webhook

controllerName: msm-controller

controllerDeployment: controller

cniImage:
  name: ciscolabs/msm-cni
  tag: latest

proxyImage:
  name: ciscolabs/msm-proxy
  tag: latest

stubImage:
  name: ciscolabs/msm-rtsp-stub
  tag: latest

webhookImage:
  name: ciscolabs/msm-admission-webhook
  tag: latest

controllerImage:
  name: ciscolabs/msm-controller
  tag: latest
