# change this to desired Kubernetes Distribution e.g. "K8S" or "K3S"
kubernetesDistro: "K8S"

nodeSelector: "{{ if eq .Values.kubernetesDistro \"K8S\" }}{{ else if eq .Values.kubernetesDistro \"K3S\" }}true{{ end }}"

controllerUrl: "http://10.96.3.1:9000"

cniImage:
  name: ghcr.io/media-streaming-mesh/msm-cni
  tag: latest

proxyImage:
  name: ghcr.io/media-streaming-mesh/msm-dp
  tag: latest

stubImage:
  name: ghcr.io/media-streaming-mesh/msm-rtsp-stub
  tag: latest

webhookImage:
  name: ghcr.io/media-streaming-mesh/msm-admission-webhook
  tag: latest

controllerImage:
  name: ghcr.io/media-streaming-mesh/msm-cp
  tag: latest

networkControllerImage:
  name: ghcr.io/media-streaming-mesh/msm-nc
  tag: latest

config:
  rtpPort: 8050
  gRPCPort: 9000