kubernetesDistro: "K8S" #change this to desired Kubernetes Distribution e.g. "K8S" or "K3S"

nodeSelector: "{{ if eq .Values.kubernetesDistro \"K8S\" }}{{ else if eq .Values.kubernetesDistro \"K3S\" }}true{{ end }}"

namespace: "{{ if eq .Values.kubernetesDistro \"K8S\" }}default{{ else if eq .Values.kubernetesDistro \"K3S\" }}gbear{{ end }}"  #change the gbear to desired namespace for K3S.

cniClusterRole: msm-cni

cniConfigMap: msm-cni-config

webhookClusterRole: msm-admission-webhook-role

webhookClusterRoleBinding: msm-admission-webhook-binding

webhookServiceAccount: msm-admission-webhook-sa

gatewayDaemonSet: msm-gateway

gatewayName: gateway

webhookDeployment: msm-admission-webhook

controllerName: msm-controller

controllerDeployment: controller

cniImage:
  name: ghcr.io/media-streaming-mesh/msm-cni
  tag: latest

proxyImage:
  name: ghcr.io/media-streaming-mesh/msm-dp
  tag: latest

stubImage:
  name:  ghcr.io/media-streaming-mesh/msm-rtsp-stub
  tag: latest

webhookImage:
  name: ghcr.io/media-streaming-mesh/msm-admission-webhook
  tag: latest

controllerImage:
  name: ghcr.io/media-streaming-mesh/msm-cp
  tag: latest
