apiVersion: v1
data:
  allow-snippet-annotations: "true"
kind: ConfigMap
metadata:
  labels:
    {{- include "Controller.labels" . | nindent 4 }}
  name: ingress-nginx-controller
  namespace: {{ .Release.Namespace }}
