apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    {{- include "Controller.labels" . | nindent 4 }}
  name: ingress-nginx
  namespace: gbear
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "Webhook.labels" . | nindent 4 }}
  name: ingress-nginx-admission
  namespace: gbear
