# cni-prep
apiVersion: v1
kind: ServiceAccount
metadata:
  name: msm-cni
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "MSM.labels" . | nindent 4 }}
    app: msm-cni
---
# webhook-prep
apiVersion: v1
kind: ServiceAccount
metadata:
  name: msm-admission-webhook-sa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "MSM.labels" . | nindent 4 }}

---
# cp-prep
apiVersion: v1
kind: ServiceAccount
metadata:
  name: msm-cp-sa
  labels:
    app: msm-cp
    {{- include "MSM.labels" . | nindent 4 }}
