# webhook
apiVersion: v1
kind: Service
metadata:
  name: msm-admission-webhook-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: msm-admission-webhook
    {{- include "MSM.labels" . | nindent 4 }}
spec:
  ports:
    - name: ssl
      port: 443
      targetPort: 443
  selector:
    app: msm-admission-webhook

---
#msm-control-plane-svc
apiVersion: v1
kind: Service
metadata:
  name: msm-cp
  namespace: {{ .Release.Namespace }}
  labels:
    msm: cp
    {{- include "MSM.labels" . | nindent 4 }}
spec:
  ports:
    - name: grpc
      port: {{ .Values.config.gRPCPort }}
      targetPort: {{ .Values.config.gRPCPort }}
      protocol: TCP
  selector:
    msm: cp
