# Giles Study Camera
apiVersion: apps/v1
kind: Deployment
metadata:
  name: camera-giles
  labels:
    {{- include "Camera.labels" . | nindent 4 }}
    app: {{ .Values.camera.appName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.camera.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.camera.appName }}
    spec:
      containers:
        - name: rtsp-server
          image: "{{ .Values.rtspServer.name }}:{{ .Values.rtspServer.tag }}"
          imagePullPolicy: IfNotPresent
        - name: rtsp-client
          image: "{{ .Values.rtspClient.name }}:{{ .Values.rtspClient.tag }}"
          imagePullPolicy: IfNotPresent
          command: ["ffmpeg"]
          args: ["-rtsp_transport", "tcp", "-i", "{{ .Values.camera.cameraUrl }}", "-an", "-c:v", "copy", "-f", "rtsp", "{{ .Values.camera.serverUrl }}"]
        - name: msm-rtsp-stub
          image: "{{ .Values.stubImage.name }}:{{ .Values.stubImage.tag }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: MSM_LOG_LVL
              value: "DEBUG"
            - name: MSM_CONTROL_PLANE
              value: "http://msm-controller:9000"
            - name: MSM_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MSM_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MSM_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MSM_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MSM_POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
