apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    {{- include "Camera.labels" . | nindent 4 }}
  name: {{ .Values.config.appName }}
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - backend:
          service:
            name: "{{ .Values.config.appName }}-hls"
            port:
              number: {{ .Values.camera.hlsPort }}
        path: "/{{ .Values.config.appName }}"
        pathType: Prefix
