# Giles Study Camera Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.config.appName }}
  labels:
    app: {{ .Values.config.appName }}
    {{- include "Camera.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: rtsp
      port: {{ .Values.camera.rtspPort }}
      targetPort: {{ .Values.camera.rtspPort }}
      protocol: TCP
  selector:
    app: {{ .Values.config.appName }}
---
# Giles Study Camera HLS 
apiVersion: v1
kind: Service
metadata:
  name: hls-{{ .Values.config.appName }}
  labels:
    app: {{ .Values.config.appName }}
    {{- include "Camera.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: hls
      port: {{ .Values.camera.hlsPort }}
      targetPort: {{ .Values.camera.hlsPort }}
      protocol: TCP
  selector:
    app: {{ .Values.config.appName }}
