# Giles Study Camera Service
apiVersion: v1
kind: Service
metadata:
  name: giles-study
  labels:
    app: camera-giles
    {{- include "Camera.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: rtsp
      port: 554
      targetPort: 554
      protocol: TCP
  selector:
    app: camera-giles
---
# Ammar IP Camera Service
apiVersion: v1
kind: Service
metadata:
  name: ammar-ip-cam
  labels:
    app: camera-ammar
    {{- include "Camera.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: rtsp
      port: 554
      targetPort: 554
      protocol: TCP
  selector:
    app: camera-ammar
