---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: local-pv
  labels:
    type: local
spec:
  storageClassName: local
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"